/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos.system;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author savinda
 */
public class Pos_system extends javax.swing.JFrame {

    /**
     * Creates new form Pos_system
     */
    public Pos_system() {
        initComponents();
    }
    
    Connection con; 
    PreparedStatement pst;
    ResultSet rs;
    
    public void balance(){
        int total = Integer.parseInt(subTotalBox.getText());
        int pay = Integer.parseInt(payBox.getText());
        
        int balance =  pay - total;
        
        balanceBox.setText(String.valueOf(balance));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TotalBox = new javax.swing.JTextField();
        productCodeBox = new javax.swing.JTextField();
        productNameBox = new javax.swing.JTextField();
        priceBox = new javax.swing.JTextField();
        qtyBox = new javax.swing.JSpinner();
        addBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        balanceBox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        subTotalBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        payBox = new javax.swing.JTextField();
        calculate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 70, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Code");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 32, 130, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 150, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Qty");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 70, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 70, 20));

        TotalBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalBoxActionPerformed(evt);
            }
        });
        jPanel1.add(TotalBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 110, 30));

        productCodeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productCodeBoxActionPerformed(evt);
            }
        });
        productCodeBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productCodeBoxKeyPressed(evt);
            }
        });
        jPanel1.add(productCodeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));
        jPanel1.add(productNameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 110, 30));
        jPanel1.add(priceBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 110, 30));

        qtyBox.setRequestFocusEnabled(false);
        qtyBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                qtyBoxStateChanged(evt);
            }
        });
        jPanel1.add(qtyBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 40, 30));

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 13, 780, 200));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Total");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 13, -1, -1));

        balanceBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceBoxActionPerformed(evt);
            }
        });
        jPanel2.add(balanceBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 110, -1));

        jLabel7.setText("pay");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));
        jPanel2.add(subTotalBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 36, 110, -1));

        jLabel8.setText("balance");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));
        jPanel2.add(payBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 110, -1));

        calculate.setText("Calculate Bill");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });
        jPanel2.add(calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 360, 230));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product code", "product Name", "Qty", "Price", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 770, 390));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 260, 340, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void productCodeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productCodeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productCodeBoxActionPerformed

    private void balanceBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balanceBoxActionPerformed

    private void productCodeBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productCodeBoxKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String pCode = productCodeBox.getText();
            
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/test1","root","");
                pst = (PreparedStatement) con.prepareStatement("select * from parts where part_no = ?");
                
                pst.setString(1, pCode);
                
                rs = pst.executeQuery();
                
                //if product id not available
                if(rs.next() == false){
                    JOptionPane.showMessageDialog(this, "product code not found");
                }else{
                    String pname = rs.getString("description");
                    String price = rs.getString("price");
                    
                    productNameBox.setText(pname.trim());
                    priceBox.setText(price.trim());
                }
                
                        } catch (ClassNotFoundException ex) {
                Logger.getLogger(Pos_system.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Pos_system.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_productCodeBoxKeyPressed

    private void qtyBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_qtyBoxStateChanged
        
        int qty = Integer.parseInt(qtyBox.getValue().toString());
        int price = Integer.parseInt(priceBox.getText());
        
        int total = qty * price;
        
        TotalBox.setText(String.valueOf(total));
        
    }//GEN-LAST:event_qtyBoxStateChanged

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        
        DefaultTableModel model = new DefaultTableModel();
        
        model = (DefaultTableModel)jTable.getModel();
        
        model. addRow(new Object[]
        {
            productCodeBox.getText(),
            productNameBox.getText(),
            qtyBox.getValue().toString(),
            priceBox.getText(),
            TotalBox.getText(),
        } 
                );
        
        int sum =  0 ;
        
        for (int i = 0; i<jTable.getRowCount(); ++i){
            sum = sum + Integer.parseInt(jTable.getValueAt(i, 4).toString());
        }
        
        subTotalBox.setText(Integer.toString(sum));
        
            productCodeBox.setText("");
            productNameBox.setText("");
            qtyBox.setValue(0);
            priceBox.setText("");
            TotalBox.setText("");
            
    }//GEN-LAST:event_addBtnActionPerformed

    private void TotalBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalBoxActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
       
        balance();
        
    }//GEN-LAST:event_calculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pos_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pos_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pos_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pos_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pos_system().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TotalBox;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField balanceBox;
    private javax.swing.JButton calculate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField payBox;
    private javax.swing.JTextField priceBox;
    private javax.swing.JTextField productCodeBox;
    private javax.swing.JTextField productNameBox;
    private javax.swing.JSpinner qtyBox;
    private javax.swing.JTextField subTotalBox;
    // End of variables declaration//GEN-END:variables
}
